slam_toolbox:
  ros__parameters:
    use_sim_time: false
    enable_interactive_mode: true
    publish_map: true
    map_start_at_dock: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"  # Should match the child frame from odom->base_footprint TF
    scan_topic: "/scan"
    transform_publish_period: 0.1
    map_start_pose: [0.0, 0.0, 0.0]
    transform_tolerance: 0.2
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    map_update_interval: 0.5
    do_loop_closing: true
    use_scan_matching: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.087