rplidar_node:
  ros__parameters:
    serial_port: "/dev/lidar_uart"
    serial_baudrate: 460800
    frame_id: "laser_frame"
    inverted: false
    angle_compensate: true
    scan_mode: "Standard"
    auto_standby: false
    max_distance: 12.0
    scan_frequency: 10.0
    timeout: 2.0